export const HOME="OZER STORE"
export const CART="Cart"
export const CATEGORIES="Categories"
export const FAVORITES="Favorites"
export const PROFILE="Profile"
export const TAB="TAB"
export const PRODUCT_LIST="Product List"
export const PRODUCT_DETAIL="Product Detail"